---
- name: Create directory
    ansible.builtin.file:
      state: directory
      path: /var/www/html
      mode: '0755'

- name: Install httpd and firewalld
    ansible.builtin.apt:
      name:
        - httpd
        - firewalld
      state: latest

- name: Enable Firewall
    ansible.builtin.services:
      name: firewalld
      enabled: true
      state: started

- name: Firewalld permit httpd service
    ansible.posix.firewalld:
      service: http
      permanent: true
      state: enabled
      immediate: yes

- name: Enabling and running httpd
    ansible.buitin.services:
      name: httpd
      enabled: true
      state: started
